services:
  engine:
    image: ghcr.io/eugaelgomes/weave-engine:latest
    restart: always
    env_file:
      - path: ./.env
        required: false
      - path: ./weave-engine/.env
        required: false
    environment:
      - NODE_ENV=production
      - DOPPLER_CONFIG=prd
      - NODE_OPTIONS=--max-old-space-size=384
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
