services:
  engine:
    build:
      context: ./weave-engine
      dockerfile: Dockerfile
    restart: always
    env_file:
      - path: ./.env
        required: false
      - path: ./weave-engine/.env
        required: false
    environment:
      - NODE_ENV=production
      - DOPPLER_CONFIG=prd
