services:
  worker:
    build:
      context: ./weave-worker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - path: ./weave-worker/.env
        required: false
    environment:
      - NODE_ENV=production
      - DOPPLER_CONFIG=prd
