services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

  server:
    build:
      context: ./weave-api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - path: ./.env
        required: false
      - path: ./weave-api/.env
        required: false
    environment:
      - NODE_ENV=production
      - DOPPLER_CONFIG=prd
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
