<<<<<<< HEAD
=======
# Configuração do docker
>>>>>>> b66ba8ea6339b589fd91c661ff5f094cfc71f86d
services:
  # Backend
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./server/src
          target: /app/src
        - action: rebuild
          path: ./server/package.json
  
  # Frontend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://server:8080
    depends_on:
      - server
    networks:
      - app-network
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./web/app
          target: /app/app
        - action: rebuild
          path: ./web/package.json

  # Blog / Landing (subdomínio)
  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./blog:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_BLOG_URL=http://localhost:3001
    networks:
      - app-network
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./blog/app
          target: /app/app
        - action: rebuild
          path: ./blog/package.json

networks:
  app-network:
    driver: bridge