# docker-compose.override.yml

# Para desenvolvimento local.
services:
  server:
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
          ignore:
            - node_modules/

  blog:
    command: npm run dev

  console:
    command: npm run dev