/** @type {Record<string, string>} */
module.exports = {
  "aiReport.cta": "View full report",
  "aiReport.footer":
    "This report was automatically generated by Weave Notes AI.",
  "aiReport.intro":
    "Weave Engine generated a new report for project {projectTitle}.",
  "aiReport.preheader": "New {reportType} for {projectTitle}",
  "aiReport.sprintSuffix": " (Sprint {sprintNumber})",
  "backup.cta": "Download backup",
  "backup.info":
    "This link expires in {hours} hour(s) ({expiresLabel}) and can be used once.",
  "backup.intro1": "Your data backup was processed successfully.",
  "backup.intro2": "Use the button below to download the file.",
  "backup.outro":
    "Keep this file secure and download it from a trusted environment.",
  "backup.preheader": "Your backup is ready to download.",
  "backup.subject": "Your backup is ready to download",
  "backup.subtitle": "Data export",
  "backup.title": "Backup ready to download",
  "collab.cta": "Open note",
  "collab.intro": "{ownerName} added you as a collaborator.",

  "collab.outro":
    "If you did not expect this invitation from {ownerName}, you can ignore this email.",
  "collab.permission": "Collaboration permission is active to view and edit.",
  "collab.preheader": "You were added as a note collaborator.",
  "collab.subject": "New collaboration: {noteName}",
  "collab.subtitle": "Note sharing",
  "collab.title": "New note collaboration",
  "common.autoFooter":
    "This email was sent automatically. Please do not reply.",
  "common.brandName": "Weave Notes",
  "common.content": "Content",
  "common.contentNotesBlocks": "active notes and blocks",

  "common.ctaHint":
    "Use the button in this email to continue (open in your browser if needed).",
  "common.currentEmail": "Current email",
  "common.dueDate": "Due date",
  "common.format": "Format",
  "common.formatCsv": "CSV (Excel/Google Sheets)",
  "common.greetingFallback": "there",
  "common.newEmail": "New email",
  "common.note": "Note",
  "common.organization": "Organization",

  "common.project": "Project",
  "common.role": "Role",
  "common.username": "Username",
  "deleteMessage.bodyDetail": "All linked data was permanently erased.",
  "deleteMessage.bodyUser": "Removed user",
  "deleteMessage.footer":
    "You received this email as confirmation of your account deletion.",
  "deleteMessage.intro":
    "Your Weave Notes account was permanently deleted as requested.",
  "deleteMessage.outro":
    "If you do not recognize this action, contact our support immediately.",
  "deleteMessage.preheader": "Your account was deleted successfully.",

  "deleteMessage.subject": "Account deleted successfully - Weave Notes",
  "deleteMessage.subtitle": "Deletion confirmation",
  "deleteMessage.title": "Account deleted",
  "deleteRequest.bodyDetail":
    "After confirmation, your data and settings will be permanently removed.",
  "deleteRequest.cta": "Confirm account deletion",
  "deleteRequest.footer":
    "You received this email because a deletion request was made for this account.",
  "deleteRequest.info": "This link expires in 7 days ({expiration}).",
  "deleteRequest.intro1":
    "We received a request to permanently delete your account.",
  "deleteRequest.intro2":
    "If you want to proceed, confirm with the button below.",
  "deleteRequest.outro":
    "If you did not request this deletion, ignore this email and consider changing your password.",
  "deleteRequest.preheader": "Account deletion confirmation.",

  "deleteRequest.subject": "Account deletion confirmation - Weave Notes",
  "deleteRequest.subtitle": "Irreversible action",
  "deleteRequest.title": "Confirm account deletion",
  "dueReminder.cta": "Open note",
  "dueReminder.info": "We recommend reviewing the note today to avoid delays.",
  "dueReminder.intro":
    "The note \"{noteTitle}\" is due tomorrow ({dueDateLabel}).",
  "dueReminder.preheader": "Reminder for your note deadline.",
  "dueReminder.subject": "Reminder: due tomorrow - {noteTitle}",
  "dueReminder.subtitle": "Note due date",

  "dueReminder.title": "Deadline reminder",
  "dueReminder.untitled": "Note",
  "invite.cta": "Accept invitation",
  "invite.info": "This invitation expires in 7 days.",
  "invite.intro": "{inviterName} invited you to join {organizationName}.",
  "invite.preheader": "Invitation to join an organization.",
  "invite.subject": "Invitation to {organizationName} - Weave Notes",

  "invite.subtitle": "Organization invitation",
  "invite.title": "You have been invited",
  "inviteAccepted.cta": "Go to Home",
  "inviteAccepted.feature1": "Create notes and organize ideas with blocks.",
  "inviteAccepted.feature2":
    "Work on projects with stages, priorities, and deadlines.",
  "inviteAccepted.feature3": "Share content and collaborate with your team.",
  "inviteAccepted.feature4":
    "Centralize files, links, and context in one place.",
  "inviteAccepted.featuresIntro": "With Weave Notes you can:",
  "inviteAccepted.intro1":
    "Your access was confirmed and you can now use Weave Notes.",
  "inviteAccepted.intro2": "Plan, execute, and collaborate in one place.",
  "inviteAccepted.preheader": "Invitation accepted successfully.",
  "inviteAccepted.subject": "Welcome to {organizationName} - Weave Notes",

  "inviteAccepted.subtitle": "Your account is ready",
  "inviteAccepted.title": "Welcome to {organizationName}",
  "project.cta": "Open projects",
  "project.footer":
    "You received this email because you were added to a project on Weave Notes.",
  "project.intro":
    "{addedByName} added you as a collaborator on the project below.",
  "project.outro": "You can now view and collaborate on the project.",
  "project.preheader": "You were added to a project.",
  "project.subject": "{firstName}, you were added to project \"{projectName}\"",
  "project.subtitle": "Project collaboration",

  "project.title": "New project shared with you",
  "project.untitled": "Untitled",
  "reportType.analysis": "Analysis",
  "reportType.daily_standup": "Daily Standup",
  "reportType.deadline_alert": "Deadline Alert",
  "reportType.default": "AI Report",
  "reportType.sprint_kickoff": "Sprint Kickoff",
  "reportType.sprint_review": "Sprint Review",

  "rescue.cta": "Reset password",
  "rescue.info": "This link expires in 1 hour.",
  "rescue.intro1": "We received a request to reset your account password.",
  "rescue.intro2":
    "If you made this request, use the button below to continue.",
  "rescue.outro":
    "If you did not request this change, ignore this email. No changes will be made.",
  "rescue.preheader": "Password reset request.",
  "rescue.subject": "Password reset - Weave Notes",
  "rescue.subtitle": "Account security",
  "rescue.title": "Password reset",

  "reset.cta": "Confirm new email",
  "reset.info": "This link expires in 1 hour.",
  "reset.intro1": "We received a request to change your account email.",
  "reset.intro2": "Use the button below to validate this change.",
  "reset.outro":
    "If you did not request this change, please ignore this email.",
  "reset.preheader": "Confirm your account email change.",
  "reset.subject": "Email change validation - Weave Notes",
  "reset.subtitle": "Account security",

  "reset.title": "Confirm email change",
  "role.admin": "Administrator",
  "role.guest": "Guest",
  "role.member": "Member",
  "role.owner": "Owner",

  "role.super_admin": "Super administrator",
  "role.viewer": "Viewer",
  "welcome.cta": "Activate account",
  "welcome.footer":
    "You received this email because you created a Weave Notes account.",
  "welcome.info": "This link expires in 7 days.",
  "welcome.intro1": "Your account was created successfully.",

  "welcome.intro2":
    "To start using the platform, confirm your email with the button below.",
  "welcome.outro1": "If you did not sign up, please ignore this email.",
  "welcome.preheader": "Activate your Weave Notes account.",
  "welcome.subject": "Welcome to Weave Notes - Activate your account",
  "welcome.subtitle": "Account activation",
  "welcome.title": "Welcome to Weave Notes",
};
