# ============================
# Development Dockerfile
# ============================
FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache curl gnupg \
  && (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh

ENV DOPPLER_CONFIG_DIR=/tmp/.doppler

COPY package*.json ./
RUN npm ci

COPY . .

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 8081

ENV PORT 8081
ENV HOSTNAME "0.0.0.0"
ENV DOPPLER_CONFIG dev

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["doppler", "run", "--project", "weave-worker", "--config", "dev", "--", "npm", "start"]