name: Node CI

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory where the Node app is located'
        required: true
        type: string
      node_version:
        description: 'Node version'
        required: false
        type: string
        default: '20'
      command:
        description: 'NPM command to run (e.g. npm run build, npm run check)'
        required: true
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run command
        run: ${{ inputs.command }}
